### ISSUE TITLE
Testing Livepeer App's functionality for receiving / sending LPT Stake

### ISSUE THREAD

**Issue by chrishobcroft** [willjgriff/solidity-livepeer-aragon-app#1]
To test:

- Sending LPT to the Livepeer App using "Transfer In" functionality in the app
- Sending LPT directly to the Livepeer App from my own account using MetaMask
- Sending LPT directly to the Livepeer App from the Finance App

- Sending LPT to my own account using "Transfer Out" functionality in the app
- Sending LPT to the DAO's Vault using "Transfer Out" functionality in the app

**Comment by chrishobcroft** [comment]
Observations / Notes:

- All tests passed successfully, behaving as expected.

- Sending a "Transfer Out" from the Livepeer App to the address for the Finance App results in the LPT getting stuck in some kind of limbo - in the Finance App address, but not manageable by the finance app itself. This is more of a flaw in Aragon than Livepeer App, as I believe it's counter-intuitive that it's not possible to send tokens to the Finance App address...

- When using the "Transfer Out" functionality, the only record of the transfer appears in the Voting section (if a vote was carried out). This is less optimal than using the Withdrawal feature in the "Finance App" which displays a full list of all outbound payments. It makes me think that the only way to "Transfer Out" funds from the Livepeer App ought to be to the Finance App / Vault, so that funds can then be managed transparently with a full consolidated audit trail by the Aragon Finance App - independent of the Livepeer App.

- Token balances sometimes took some time to update, even after a refresh. They updated much more quickly in the Livepeer Explorer interface. Also, sometimes one figure would update and then another would reset to 0, then take more time to update to the correct value.

**Comment by willjgriff** [comment]
Point one, this requires more investigation, I'm not currently sure what address is appropriate to send LPT directly too from the Livepeer App in order for it to appear in the finance app. Originally I thought the vault but after experimenting it doesn't look like you can send it either the vault or the finance app's address. Will look into it at some point.

Point two, the only way to do this is to call a function which will move ALL the Livepeer App's LPT to the DAO's vault, then they can be managed from the finance app. Note that it has to move it all. A button could be added to do this.

Again, recently updated event triggers so hopefully this won't happen anymore. Will keep an eye for it though. Bring it up if it's seen again.
